### ISSUE TITLE
Module 02-IAM, section 1 wording is confusing

### ISSUE THREAD

**Issue by deathstarjanitor** [terraform-google-modules/cloud-foundation-training#16]
Wording in section 1 suggests to create a binding for a 'user' and 'group' but I believe the intent of this portion is to add a set of roles to the service account created in earlier portions.

Perhaps this could be reworded to be more clear.

**Comment by deathstarjanitor** [comment]
Also worth noting that if you run this module against your service account, the final step of terraform destroy will remove necessary permissions from the Service Account

**Comment by zefdelgadillo** [comment]
The intent is to create bindings for another user to demonstrate IAM bindings using CFT - not necessarily to set permissions on the service account used for your lab (which happen via setup). Will update the wording to make this more clear.
