### ISSUE TITLE
Error: storage.NewClient() failed: dialing: google: could not find default credentials. 

### ISSUE THREAD

**Issue by alanranciato** [terraform-google-modules/cloud-foundation-training#18]
Using pixelbook terminal
Using personal project (not training)

**Happening in all modules:**

exported credential per command 
`export GOOGLE_CLOUD_KEYFILE_JSON="$(pwd)/cft-training.json"`

Received error **Error: storage.NewClient() failed: dialing: google: could not find default credentials.**  when running `terraform init`

Added 
`credentials = "../cft-training.json"` to backend.tf to fix

**Comment by zefdelgadillo** [comment]
Similar to #15. Including steps to run `gcloud auth application-default login`
