### ISSUE TITLE
04-Instance-Group: Fix Service Account Typo

### ISSUE THREAD

**Issue by mbachari** [terraform-google-modules/cloud-foundation-training#27]
In **main.tf** and **iam.tf** we reference the service account as
`sa-cft-training@${var.project_id}.iam.gserviceaccount.com`
It should be
`cft-training@${var.project_id}.iam.gserviceaccount.com`
without **`sa-`** as in the 00-Setup lab and subsequent labs

**Comment by bharathkkb** [comment]
@mbachari I believe we are moving towards `sa-cft-training`, and we should fix  00-Setup lab to create `sa-cft-training` instead of `cft-training`. Happy to accept a PR if you have bandwidth :)

**Comment by mbachari** [comment]
sounds good, let met get through all the labs and then I'll submit a PR after making sure no broken references are there
