### ISSUE TITLE
IAM conditions not supported with GCP provider 3.9.0

### ISSUE THREAD

**Issue by wintwoo** [terraform-google-modules/cloud-foundation-training#33]
The examples use GCP provider v3.9.0, which doesn't appear to support IAM conditions in google_project_iam_binding.  This breaks Lab 2 (IAM), and maybe some others as well.

Error: Unsupported block type

  on .terraform/modules/project_iam_bindings/modules/projects_iam/main.tf line 37, in resource "google_project_iam_binding" "project_iam_authoritative":
  37:   dynamic "condition" {

**Comment by bharathkkb** [comment]
Thanks for the report @wintwoo 
I have fixed this via #31 Please try again if you get a chance.
