### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/cloud-foundation-training#7]
I stumbled upon this course while browsing through the Google Terraform modules. Here's some minor things that I discovered along the way:

- The license note at the start of every file is a bit distracting
- Instance group chapter: 
  - `main.tf` contains the word "moduel"
  - the readme for task 1 contains a dead link (https://github.com/terraform-google-modules/terraform-google-vm/modules/instance_template)
- Load balancer chapter
  - `main.tf`: `protcol` (missing second "o")

**Comment by morgante** [comment]
Thanks for feedback, I've opened a PR to fix the typos.

Unfortunately we have to keep the license note to comply with Google open source policies.
